.github/workflows/alex.yml

Add Alex github action

---

.github/workflows/publish.yml

Add github pages publishing task

Add build step

---

.gitignore
docs/api.md

update git ignore to exclude additional generated files

Update git ignore

---

.github/workflows/docusaurus.yml
.github/workflows/publish.yml
Makefile

Add test step for build on PRs

---

CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
SECURITY.md

Add project governance docs

---

docusaurus.config.js

Update edit url

---

docusaurus.config.js

Update edit url, again

---

CODEOWNERS
blog/2020-03-06-influx-perf.md
blog/2020-08-06-to-async-or-not-to-async.md
blog/2020-10-16-v09-release.md
blog/2021-06-29T17-LFX-Blog-Jigyasa-gcloud.md
blog/2021-07-06-Blog-Rohit-Property-Based-Testing.md
blog/2021-07-14-continuous-benchmarking.md
docs/Operations/linked-transports.md
docs/Workshop/examples/14_syslog_udp/README.md
docs/Workshop/examples/15_syslog_udp_dns/README.md
docs/Workshop/examples/30_servers_lt_http/README.md
docs/Workshop/examples/31_servers_lt_ws/README.md
docs/Workshop/examples/32_proxies_lt_http/README.md
docs/Workshop/examples/33_proxies_lt_ws/README.md
docs/Workshop/examples/34_bridges_lt_http_ws/README.md
docs/Workshop/examples/35_reverse_proxy_load_balancing/README.md
docs/Workshop/examples/36_quota_service/README.md
docs/Workshop/examples/37_configurator/README.md
docs/Workshop/examples/38_polling_alerts/README.md
docs/Workshop/examples/39_kafka_elastic_correlation/README.md
docs/Workshop/examples/42_otel_jaeger/README.md
docs/Workshop/examples/43_otel_prometheus/README.md
docs/Workshop/examples/44_otel_elastic_apm/README.md
docs/index.md
package-lock.json
package.json
src/components/HomepageFeatures.js

* fix `workshop` -> `Workshop`
* fix remaining `../static` links
* update CODEOWNERS
* update docusaurus

Update and fix more broken links

---

docusaurus.config.js
package-lock.json
package.json

Add search using https://github.com/cmfcmf/docusaurus-search-local

Add search plugin

---

.github/workflows/docusaurus.yml
CNAME.txt
docusaurus.config.js

cache the right directory and fix outdated logo link

Improve caching and fix broken link

---

community/teams.md

Add the docs team and add Sharon as a maintainer on it.

Add docs team

---

blog/2021-02-12-v010-release.md

Add v0.10 release blog.
Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

Add left out blog

---

community/governance/Contributing.md

Draft content for technical writing contributions for community section

---

community/Events/TremorCon2021.md
community/community.md
community/eventsandmedia.md
docusaurus.config.js

Add events and media section and seed with tremorcon YT links

---

docs/recipes/_category_.yaml

Fix typo and change Receipes to Recipes

---

community/getting-started/getting-started.md

Content roughly stayed the same; however, I rewrote a lot of the instructions using more active language that adhered to a style guide. Deleted some text I thought was superfluous and negatively impacted the professionalism of the document. I will hope to revisit this page later on when we have a better sense of how the documentation hierarchy will be reorganized and content re-allocated.

Language Rewrite in Getting Started Page

---

community/governance/Versioning.md

Initial draft of versioning and sundown policy for governance section

---

.github/workflows/broken-link-check.yml

Add periodic checks for dead links so we don't have to do that manually

Check page for dead links periodically

---

docs/artefacts/offramps.md
docs/artefacts/onramps.md
versioned_docs/version-0.11/artefacts/offramps.md
versioned_docs/version-0.11/artefacts/onramps.md

We use librdkafka 1.5.2 on main and on 0.11.7

Update librdkafka version referenced in onramp and offramp docs

---

docusaurus.config.js

Fix faq and events link

---

docs/artefacts/offramps.md
docs/artefacts/onramps.md
versioned_docs/version-0.11/artefacts/offramps.md
versioned_docs/version-0.11/artefacts/onramps.md

We upgraded to 1.6.1, not 1.5.2. My bad!

Update to correct librdkafka version 1.6.1 currently in use for 0.11 and main

---

docusaurus.config.js

use a SSL enabled url for benchmars

Fix URL for bench bar

---

src/components/Benchmark.js
src/pages/benchmarks.js

Fix chart rendering

---

docs/artefacts/postprocessors.md
docs/artefacts/preprocessors.md
openapi.yaml

This pull request will fix this [issue](https://github.com/tremor-rs/tremor-www/issues/139).
Work done within this pull request will updated the list of supported pre & post processors listed in the `openapi.yaml` file.

feat: updated pre & post processors

---

rfc/accepted/0020-troy.md

Signed-off-by: Darach Ennis <dennis@wayfair.com>

Add stale troy RFC from legacy tremor-rfcs repo

---

docs/operations/monitoring.md

fix comment spelling

---

.gitpod.Dockerfile
.gitpod.yml

Add support for gitpod

---

docusaurus.config.js
src/css/custom.css

Signed-off-by: Shashank-Jha <jhashashank007@rediffmail.com>
Here are some changes I made,
1. Improved the dark mode color combination and made the links visible. ✅
2. Improved the Active sidebar nav on both sides.✅
3. Changed Darkmode Homepage✅
Screenshots of the changes are attached below 🔽

Improved docs UI

---

docs/reference/connectors/gpubsub_consumer.md

Signed-off-by: Ramona Luczkiewicz <rluczkiewicz@wayfair.com>

Add documentation for Google PubSub Consumer

---

docs/guides/basics.md

Casing was inconsistent + `eany` typo

Small fix in code snippet

---

package-lock.json
package.json

Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

Update to Docusaurus v2.0.0-beta.21

---

docs/guides/index.md
versioned_docs/version-0.12/guides/index.md

Fox the typo, yes I'm committing to this 🦊

---

docs/reference/connectors/elastic.md

See: https://github.com/tremor-rs/tremor-runtime/pull/1740

Add docs for more ES options.

---

docs/guides/code/metrics/05_tdengine/docker-compose.yaml
versioned_docs/version-0.12/guides/code/metrics/05_tdengine/docker-compose.yaml

latest version always better than previous :)

update tdengine to 2.6.0.4 and grafanaplugin to 3.2.5

---

docs/reference/connectors/gpubsub_consumer.md
docs/reference/connectors/gpubsub_producer.md

Signed-off-by: Ramona Luczkiewicz <rluczkiewicz@wayfair.com>

Add documentation for the gpubsub producer

---

blog/2022-06-15-tdengine-colaboration.md

Add a post about our collaboration with TDengine.

Add TDEngine colab blog post

---

src/components/HomepageFeatures.js

Fix broken hero links on landing page - oops

Fix hero links

---

docs/reference/postprocessors/compress.md

Tremor now supports compression level for some algorithms, this PR updates the docs  to reflect the changes.
Signed-off-by: Omkar Mohanty <franzohouser@gmail.com>

Update compression docs

---

src/pages/benchmarks.js

Signed-off-by: Mario <marioortizmanero@gmail.com>

Fix typos in benchmarks page

---

docs/reference/connectors/clickhouse.md

For some reason, my previous pr (#183) got closed, so I'm opening this one instead :)

ClickHouse connector documentation

---

blog/2022-07-07-LFX-Blog-Sasha.md

This blogpost gives an overview of what I did during the mentorship. I'd love to get feedback and publish it in the Tremor blog!

LFX end of mentorship blogpost

---

docs/reference/connectors/gcl_writer.md

Add  gcl_writer connector reference doc

---

docs/reference/connectors/gcl_writer.md

Fix some values in the gcl writer example

---

docs/concepts/runtime_capabilities.md

Improve description of guaranteed delivery mechanics based on feedback.

Improve GD section

---

docs/reference/connectors/gcs_streamer.md
docs/reference/connectors/s3.md

to reflect changes for only ever acking upon a finished upload.

Update s3_streamer and gcs_streamer docs

---

docs/reference/connectors/gbq.md

Signed-off-by: Ramona Łuczkiewicz <rluczkiewicz@wayfair.com>

Document request_size_limit in GBQ

---

.github/workflows/depandabot-auto-merge.yaml

Fix the auto merge script for dependabot

Fix dependabot token

---

docs/reference/connectors/gbq.md

Signed-off-by: Ramona Łuczkiewicz <rluczkiewicz@wayfair.com>

Document multi-table writes

---

docs/reference/codecs/statsd.md

Signed-off-by: Mariano Guerra <mariano@marianoguerra.org>

Fix wording in statsd docs

---

docs/operations/configuration.md

Signed-off-by: Mariano Guerra <mariano@marianoguerra.org>

Fix mispelling

---

static/language/prolog/WindowKind.md

Signed-off-by: Mario Ortiz Manero <marioortizmanero@gmail.com>

Fix typo in sliding windows

---

package-lock.json
package.json

Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

Update to Docusaurus v2.2.0

---

docs/reference/connectors/common_configuration.md
docs/reference/connectors/index.md
docs/reference/connectors/s3.md
docs/reference/connectors/tcp.md
docs/reference/connectors/udp.md
docs/reference/connectors/unix_socket.md
docs/reference/connectors/ws.md

See https://github.com/tremor-rs/tremor-runtime/pull/2078

Document socket options

---

docs/reference/connectors/http.md

Update documentation to reflect codec behaviour for HTTP conenctors

Update HTTP config docs

---

docs/reference/codecs/json-sorted.md
docs/reference/codecs/json.md
docs/reference/extractors/json.md

See https://github.com/tremor-rs/tremor-runtime/pull/2107

Add note about json extractor and codec deduplicating keys

---

docs/language/pipelines.md

documentation for state windows

Add documentation for state windows

---

community/ADOPTERS.md
community/case-studies.md

Issue coming up...
Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

Add Adopters of Tremor

---

versioned_docs/version-0.12/getting-started/index.md

Fixing broken links to other pages. 
Signed-off-by: Dean <22192242+saintdle@users.noreply.github.com>

Fixing broken links on getting started pages

---

versioned_docs/version-0.12/guides/basics.md

Signed-off-by: Abhinav-MA <63648644+Abhinav-MA@users.noreply.github.com>

Update basics.md- spelling mistake

---

Makefile
package-lock.json
package.json

Update dependencies, refactor Makefile to allow the docusaurus page to be build from the tremor-runtime CI so we can test doc generation.

Tremor ci inclusion

---

docs/guides/basics.md

Fixed Documentation Typo

---

versioned_docs/version-0.12/guides/basics.md

the 'flow' keyword should be ahead of the implementation

Update basics.md - misplaced flow statement

---

versioned_docs/version-0.12/guides/basics.md

Fix pwd to PWD as spotted by @devskillz47 in #336 ( giving github.dev online editor a whirl for a quick PR ... )

Fix pwd to PWD in basic runner guide in v12 docs

---

community/development/index.md
community/development/quick-start.md
docs/getting-started/install.md
versioned_docs/version-0.12/getting-started/install.md

- installation instructions version change
- windows installation instructions header
- rust installation instructions clarification

Various getting started instruction improvements
